# Generated by Django 4.0.3 on 2022-08-06 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=13, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market_name', models.CharField(max_length=100, null=True, unique=True)),
                ('Market_Address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('order_note', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.district')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.market')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thana_name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Retail_name', models.CharField(max_length=100, null=True, unique=True)),
                ('Retail_Address', models.CharField(max_length=200, null=True)),
                ('DMS_Code', models.CharField(max_length=100, null=True)),
                ('RD_name', models.CharField(max_length=100, null=True)),
                ('RD_DMS', models.CharField(max_length=100, null=True)),
                ('Created_Date', models.DateField()),
                ('Created_By', models.CharField(max_length=100, null=True)),
                ('Modified_Date', models.DateField(blank=True)),
                ('Modified_By', models.CharField(blank=True, max_length=100)),
                ('District_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.district')),
                ('Market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.market')),
                ('Thana_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.thana')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=100, null=True, unique=True)),
                ('regular_price', models.FloatField(max_length=100, null=True)),
                ('inventory_id', models.IntegerField(null=True)),
                ('discount_price', models.FloatField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('available_stock', models.IntegerField()),
                ('image_location', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='retail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.retail'),
        ),
        migrations.AddField(
            model_name='order',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.thana'),
        ),
    ]
