# Generated by Django 4.0.3 on 2022-08-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market_name', models.CharField(max_length=100, null=True, unique=True)),
                ('Market_Address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thana_name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retail_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Retail_name', models.CharField(max_length=100, null=True, unique=True)),
                ('Retail_Address', models.CharField(max_length=200, null=True)),
                ('DMS_Code', models.CharField(max_length=100, null=True)),
                ('RD_name', models.CharField(max_length=100, null=True)),
                ('RD_DMS', models.CharField(max_length=100, null=True)),
                ('Created_Date', models.DateField()),
                ('Created_By', models.CharField(max_length=100, null=True)),
                ('Modified_Date', models.DateField(blank=True)),
                ('Modified_By', models.CharField(blank=True, max_length=100)),
                ('District_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.district')),
                ('Market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.market')),
                ('Thana_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.thana')),
            ],
        ),
    ]
