# Generated by Django 4.0.3 on 2022-08-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_district_market_thana_retail_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retail_List',
            new_name='Retail',
        ),
    ]
